# This confirms that the repo is properly documented according
# to the information located in README-HEADER.md

name: Document

on:
  pull_request:
    # Run tests when PRs opened or updated
    types: [opened, synchronize]
    branches:
      - main
concurrency: document-${{ github.base_ref }}
jobs:
  document:
    name: "Document"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: "Checkout"
        uses: actions/checkout@main

      # This makes it easier to push changes back to the PR
      - name: "Checkout w/ gh"
        run: gh pr checkout ${{ github.event.pull_request.number}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup asdf
        uses: asdf-vm/actions/setup@v3

      - name: Cache asdf
        id: asdf-cache
        uses: actions/cache@v3
        with:
          path: ~/.asdf/
          key: ${{ runner.os }}-${{ hashFiles('**/.tool-versions') }}

      - name: Setup asdf
        if: steps.asdf-cache.outputs.cache-hit != 'true'
        uses: asdf-vm/actions/install@v3

      - name: "Generate documentation"
        run: ./scripts/document.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Commit if Necessary"
        run: |
          if [[ "$(basename "$(git rev-parse --show-toplevel)")" != *'terraform-aws-template'* ]]; then
            echo "Setting core.fileMode to false to avoid false positives in documentation check."
            git config core.fileMode false
            if [[ -n $(git status --porcelain) ]]; then
              echo "Documentation is not up to date. Comitting updates"

              git add README.md
              git config user.name "${GITHUB_USERNAME}"
              git config user.email "${GITHUB_USERNAME}@users.noreply.github.com"
              git commit -m "Running document script"
              git push
            fi
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ github.actor }}
