# This confirms that the repo is properly formatted according
# to the information located in README-HEADER.md

name: Format

on:
  pull_request:
    # Run tests when PRs opened or updated
    types: [opened, synchronize]
    branches:
      - main
concurrency: format-${{ github.base_ref }}
jobs:
  format:
    name: "Format"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: "Checkout"
        uses: actions/checkout@main

      - name: Setup asdf
        uses: asdf-vm/actions/setup@v3

      - name: Cache asdf
        id: asdf-cache
        uses: actions/cache@v3
        with:
          path: ~/.asdf/
          key: ${{ runner.os }}-${{ hashFiles('**/.tool-versions') }}

      - name: Setup asdf
        if: steps.asdf-cache.outputs.cache-hit != 'true'
        uses: asdf-vm/actions/install@v3

      - name: "Format"
        run: ./scripts/format.sh

      - name: "Confirm"
        run: |
          if [[ ! -z $(git status --porcelain) ]]; then
            echo "Repo is not canonically formatted. Run ./scripts/format.sh"
            exit 1
          fi
